### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by lindsaynhayes** [schwab-lab/annotateCSF#4]
using GUI on Windows 10 pro installed via instructions on part 2. Installation.
test_data set worked.

I used the prepare data feature to merge 4 folders of 10X data. That part worked great and created unified files. Then when I Run mapping it has an error and does not complete. 

Processing and QC completes
Loading reference data completes
Concatenating datasets and finding variable genes (Attribute Error)

Here is the command line from this point. 

Concatenating datasets and finding variable genes...
AnnData object with n_obs × n_vars = 17384 × 25053
    obs: 'barcode', 'orig.ident', 'condition', 'frozen', 'tissue', 'study', 'tissue_ident', 'orig.ident.new', 'doublets', 'doublet_score', 'batch', 'pbmc', 'labels', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_rp', 'log1p_total_counts_rp', 'pct_counts_rp'
    var: 'gene_symbols', 'rp', 'gene_ids-0', 'mt-1', 'n_cells_by_counts-1', 'mean_counts-1', 'log1p_mean_counts-1', 'pct_dropout_by_counts-1', 'total_counts-1', 'log1p_total_counts-1'
    layers: 'counts'
anndata\_core\anndata.py:1220: FutureWarning: The `inplace` parameter in pandas.Categorical.reorder_categories is deprecated and will be removed in a future version. Removing unused categories will always return a new Categorical object.
... storing 'condition' as categorical
anndata\_core\anndata.py:1220: FutureWarning: The `inplace` parameter in pandas.Categorical.reorder_categories is deprecated and will be removed in a future version. Removing unused categories will always return a new Categorical object.
... storing 'tissue' as categorical
anndata\_core\anndata.py:1220: FutureWarning: The `inplace` parameter in pandas.Categorical.reorder_categories is deprecated and will be removed in a future version. Removing unused categories will always return a new Categorical object.
... storing 'study' as categorical
anndata\_core\anndata.py:1220: FutureWarning: The `inplace` parameter in pandas.Categorical.reorder_categories is deprecated and will be removed in a future version. Removing unused categories will always return a new Categorical object.
... storing 'labels' as categorical
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "annotateCSF.py", line 1921, in <lambda>
  File "annotateCSF.py", line 1056, in map_to_query
  File "scanpy\preprocessing\_highly_variable_genes.py", line 444, in highly_variable_genes
  File "pandas\core\generic.py", line 5487, in __getattr__
  File "pandas\core\accessor.py", line 181, in __get__
  File "pandas\core\arrays\categorical.py", line 2600, in __init__
  File "pandas\core\arrays\categorical.py", line 2609, in _validate
AttributeError: Can only use .cat accessor with a 'category' dtype

**Comment by schwab-lab** [comment]
Dear Lindsay,

I would like to help with your issue, but we would need a lot more information to reproduce this issue.

(1) What exact version of annotateCSF are you using? And do you use the version with or without CUDA support?
(2) Do you use the Python version via start.cmd, or the compiled version via run_aCSF.exe?
(3) Did you try to use annotateCSF for mapping of the provided testing dataset (as suggested in the instructions)? It would be essential to know for sure that the software (mapping process) is able to work in your setup with controlled data.
(4) How exactly does your data look like? If I get you correctly, the first step (data preparation) does work, and it gives you some valid looking data? This data gives an issue with mapping afterwards, right? Can you please inspect the prepared data and compare it to the testing dataset? Does the structure look identical? Can you see any issues here, that could have originated from an issue in data preparation?
(5) If you cannot solve it with (1)-(4) by yourself, could you please provide us with a reduced, very small sample dataset, that gives the mapping error you describe, so that we can try and reproduce the issue on our systems?

**Comment by lindsaynhayes** [comment]
Hello thank you for your reply. 

1a. v2.2a_Win 
1b. without CUDA
2. run_aCSF.exe
3. Yes, the test_data worked fine.
4. I think the error is with how prepare data is generating the tsv files. 
I tried aCSF by writing the final Seurat object I had of the data and that worked fine.

The tsv files that are generated by the prepare data are just a single column of data. 
For example the condition.tsv from prepare data:
condition
group1
group1
...
group2
group2

The condition.tsv created from the Seurat object using `write.table(seurat_object$condition, "condition.tsv")`
"x"
"sample_cell_barcode"    "group1"
"sample_cell_barcode"    "group1"
...
"sample_cell_barcode"    "group2"
"sample_cell_barcode"    "group2"

I was worried the quotes would cause a problem because that is not in the example file format in the instructions, but it still worked ok. 

5. Extra Question: 
Is there a way to go recall a previous analysis? I wrote out the umap_coord, mapped_labels, and h5ad. Is there a way to re-load that into aCSF to make additional plots? Otherwise I can just take those annotations back into Seurat. 

Thanks for the tool!
Lindsay

**Comment by schwab-lab** [comment]
Thank you for your comments!
Yes, I also think that the data preparation is causing the issue by formatting the data in an incorrect way. Data preparation was just an "add-on" and is not a central feature of our tool. So we may (or may not) fix this some time in the future.
(As far as I get from you, a second column has to be added to condition.tsv, right?)

To (5):
Unfortunately the aCSF does not "officially" provide a method to reload an already mapped dataset. You can only do this by reloading the source files and perform the mapping again.
It is, nevertheless, possible to edit the Python script manually, save the Python workspace, reload the workspace at a later time and invoke annotateCSF's methods then. (but we cannot provide support for this, unfortunately)
Reloading analysis results without the need of a re-mapping is still a feature on our internal "whishlist", which might be implemented in the future, but it will take some time due to lack of (personal) ressources at the moment.
